import SessionProvider from "@/app/components/sessionProvider";
import QueryWrapper from "./components/queryWrapper";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="wireframe">
      <body>
        <div className="w-full prose max-w-none">
          <SessionProvider>
            <QueryWrapper>{children}</QueryWrapper>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
